### ISSUE TITLE
install failure --  ld: library not found for -locci

### ISSUE THREAD

**Issue by equinoxss** [joeferner/node-oracle#185]
I have the 11.2 instantclient package install on a mac running mavericks. I believe I have followed the setup instructions exactly, but cannot get passed this missing lib error.

NPM-DEBUG.LOG: line 93 is where things appear to go off the rails

89 verbose linkBins oracle@0.3.6
90 verbose linkMans oracle@0.3.6
91 verbose rebuildBundles oracle@0.3.6
92 info install oracle@0.3.6
93 verbose unsafe-perm in lifecycle true
94 info oracle@0.3.6 Failed to exec install script
95 info /Users/sxsmith/workspace/bender/node_modules/oracle unbuild
96 info preuninstall oracle@0.3.6
97 info uninstall oracle@0.3.6
98 verbose true,/Users/sxsmith/workspace/bender/node_modules,/Users/sxsmith/workspace/bender/node_modules unbuild oracle@0.3.6
99 info postuninstall oracle@0.3.6

STDOUT:

> oracle@0.3.6 install /Users/sxsmith/workspace/bender/node_modules/oracle
> node-gyp rebuild

  CXX(target) Release/obj.target/oracle_bindings/src/connection.o
  CXX(target) Release/obj.target/oracle_bindings/src/oracle_bindings.o
  CXX(target) Release/obj.target/oracle_bindings/src/executeBaton.o
  CXX(target) Release/obj.target/oracle_bindings/src/reader.o
  CXX(target) Release/obj.target/oracle_bindings/src/statement.o
  CXX(target) Release/obj.target/oracle_bindings/src/outParam.o
  SOLINK_MODULE(target) Release/oracle_bindings.node
ld: library not found for -locci
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/oracle_bindings.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sxsmith/workspace/bender/node_modules/oracle
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! oracle@0.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracle@0.3.6 install script.
npm ERR! This is most likely a problem with the oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracle
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "oracle"
npm ERR! cwd /Users/sxsmith/workspace/bender
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.13
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/sxsmith/workspace/bender/npm-debug.log
npm ERR! not ok code 0

**Comment by PixnBits** [comment]
can also happen if you're using the i386 downloads when the compiler is expecting x86
(at least, for me on Ubuntu 14.04LTS) (not a bug)
