### ISSUE TITLE
npm install oracle fails 

### ISSUE THREAD

**Issue by csidp** [joeferner/node-oracle#186]
npm install oracle fails

> npm --version
> 1.4.9
> node --version
> v0.10.28
> Windows 7
> .NET 4.0
> InstantClient 12.1

gyp ERR! build error
gyp ERR! stack Error: `<somePath>\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (<somePath>\nodejs\node_modules\npm\node_modules\node-gyp\lib\buil
d.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "<somePath>\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "
rebuild"
gyp ERR! cwd <otherPath>\test1\node_modules\oracle
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! oracle@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracle@0.3.7 install script.
npm ERR! This is most likely a problem with the oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracle
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "<other1Path>\\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\
\npm-cli.js" "install" "oracle"
npm ERR! cwd <otherPath>\test1
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     <otherPath>\npm-debug.log
npm ERR! not ok code 0

**Comment by AYAXGVLVI5** [comment]
@raztus Thanks. The problem was not the 12 version but that I am using a virtual machine with vagrant and precise32 under a 64 bit windows machine and the downloaded oracle drivers were for 64bit and the "compatible" ones were for 32bit of the VM. Hope this helps someone else. 

Now it installed correctly but I have another error which is:
Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor.
