### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by polleyoo** [joeferner/node-oracle#205]
I am receiving the following when attempting to install oracle via NPM. Any ideas?

ubuntu@ubuntu-VirtualBox:~/octest2$ sudo npm install oracle
[sudo] password for ubuntu: 

> oracle@0.3.7 install /home/ubuntu/octest2/node_modules/oracle
> node-gyp rebuild

make: Entering directory `/home/ubuntu/octest2/node_modules/oracle/build'
  CXX(target) Release/obj.target/oracle_bindings/src/connection.o
In file included from ../src/connection.cpp:2:0:
../src/connection.h:11:18: fatal error: occi.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/oracle_bindings/src/connection.o] Error 1
make: Leaving directory`/home/ubuntu/octest2/node_modules/oracle/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.11.0-15-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/octest2/node_modules/oracle
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! oracle@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oracle@0.3.7 install script.
npm ERR! This is most likely a problem with the oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracle
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "oracle"
npm ERR! cwd /home/ubuntu/octest2
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/octest2/npm-debug.log
npm ERR! not ok code 0

**Comment by raztus** [comment]
@ZenWindrunner read the output carefully:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
```

**Comment by dtfiedler** [comment]
Windows 7
Python 2.7

I have set the environment variables and include the instant client files in my path but I am still receiving this error:

![error](https://cloud.githubusercontent.com/assets/12800001/9012097/dd1a6ae4-3777-11e5-9501-7526751371ce.PNG)

**Comment by Jiafan** [comment]
Hey guys ,I got the same error  on  centos 6.7:

1.  system 6.7
2. gcc 4.8 
3. python 2.7
4. node 6.3 

![npm install oracle error](https://cloud.githubusercontent.com/assets/10692668/17430591/96c44aea-5b27-11e6-946e-211c40febbd9.png)
![environment](https://cloud.githubusercontent.com/assets/10692668/17430599/aaff0d4c-5b27-11e6-87e6-ec4418d0dbef.png)
![software env](https://cloud.githubusercontent.com/assets/10692668/17430600/ab08a424-5b27-11e6-8704-a3f80105ba10.png)


Could you give me some guid?
Thank you first.
