### ISSUE TITLE
Error : the specified procedure could not be found [Windows XP 32bit]

### ISSUE THREAD

**Issue by leejk9592** [joeferner/node-oracle#72]
I install node-oracle Normally using npm and make it addon by using node-gyp@0.10.9

but.. I can't use it with below error

※ "var oracle = require('oracle')" makes below error!

module.js:356 module._extensions extension (this, filename)
Error : the specified procedure could not be found
${myNodeProjectPath}\node_modules\oracle\build\Release\oracle_bindings.node
at Module.load(module.js:356:32)
at Function.Module.load(module.js:312:12)
at Module.require(module.js:364:17)
at require(module.js:380:17)
at Object.<anonymous>(${myNodeProjectPath}\node_modules\oracle\lib\oracle.js:2:16)
at Module.compile(modle.js:456:26)
at Object.Module._exrensions..js(module.js:474:10)
at Module.load(module.js:356:32)
at Function.Module._load(module.js:312:12)
at Module.require(module.js:364:17)

OS : Windows XP 32bit
Node : 0.10.9, 0.10.10, 0.10.15(All of versions I tried)
Node-gyp : 0.10.9
Oracle : 12_1
VisualStudio : VS2010
OCI_INCLUDE_DIR=C:\instantclient_12_1\sdk\include
OCI_LIB_DIR=C:\instantclient_12_1\sdk\lib\msvc\vc10
OCI_VERSION=12
Path=...;c:\instantclient_12_1\vc10;c:\instantclient_12_1

Is there anyone knows about this error?

**Comment by thaihoc** [comment]
I have a same problem. My error:

Error: The specified procedure could not be found.
D:\www\motcua.tiengiang\public\socket.io\oracle\build\Release\oracle_bindings.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\www\motcua.tiengiang\public\socket.io\node_modules
\oracle\lib\oracle.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

OS: Window Server 2008 SP1 32 bit
Node: 0.10.29
Node-gyp : 1.0.2
Oracle : 12_1
VisualStudio : VS2010 Express
OCI_INCLUDE_DIR=C:\instantclient_12_1\sdk\include
OCI_LIB_DIR=C:\instantclient_12_1\sdk\lib\msvc\vc10
OCI_VERSION=12
Path=...;c:\instantclient_12_1\vc10;c:\instantclient_12_1

Is there anyone knows about this error?
